{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "preprocessing-service-dictionary.fullname" . }}
  labels:
    {{- include "preprocessing-service-dictionary.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
