apiVersion: v1
kind: Service
metadata:
  name: {{ include "preprocessing-service-dictionary.fullname" . }}
  labels:
    {{- include "preprocessing-service-dictionary.labels" . | nindent 4 }}
    eu.gravitate-health.fosps.preprocessing: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "preprocessing-service-dictionary.selectorLabels" . | nindent 4 }}
